### ISSUE TITLE
Update code for ember1.0 and ember-data.beta1

### ISSUE THREAD

**Issue by xponrails** [mharris717/ember-pagination#1]
Hi.

I'm just tring to update your code to let it work with ember 1.0 and ember-data beta1, but without success (I'm working with ember since few days ago).

Could you please release an updated version? 

Then I didn't understand if it automatically updates the view with the new data.

Thanks for your help,

Stefano

**Comment by mharris717** [comment]
Thanks for the issue, I'll go ahead and update for 1.0

**Comment by xponrails** [comment]
Any news?

**Comment by trunda** [comment]
Hi, same question here

**Comment by mharris717** [comment]
Made ton of progress on my other ember library, Ember Auth Easy. Going to port what I learned over here shortly.

**Comment by solojavier** [comment]
How much is needed for migration?. I might me able to work on it with some direction. This seems to be what I need on a project Im working on....

**Comment by mharris717** [comment]
Hi all,

I've been having some personal issues preventing me from working on this, but it looks like I should have some time shortly. 

@solojavier Thanks for the offer, I may ping you.

Mike

**Comment by mharris717** [comment]
Make ton of progress, might even be done. Need to check and update the docs, then will post an update

**Comment by solojavier** [comment]
:+1:

**Comment by mharris717** [comment]
Should be good to go. 

README is updated, please check it for info on how to setup your controllers.

Would love feedback. Promise not to take 10 years to address again.

Mike

**Comment by solojavier** [comment]
Thanks...
